---
id: Injector
name: Injector
full: Dependency injection container library
description: A dependency injection container for Horde.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Injector
authors:
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha11
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^7.4 || ^8
    composer:
      psr/container: ^2
      horde/exception: ^3
  dev:
    composer:
      horde/test: ^3
provides:
  psr/container-implementation: 2.0.1
